### ISSUE TITLE
Relative to the compose volume is mapped incorrectly in docker compose

### ISSUE THREAD

**Issue by Vadimkin** [docker/compose-cli#1677] opened 2021-05-14 08:51 UTC
**Description**

**Steps to reproduce the issue:**
1. Create `docker-compose.yml` with next content
```
version: '3.8'
services:
    reverse:
        hostname: reverse
        image: openresty/openresty:alpine
        ports:
            - "443:443"
        volumes:
            - ./docker/nginx/conf/:/etc/nginx/conf.d/
```
2. `docker compose up`

**Describe the results you received:**
```
→ docker compose up
[+] Running 0/0
 ⠋ Container temp_reverse_1  Recreate                                                                                      0.1s
Error response from daemon: Duplicate mount point: /etc/nginx/conf.d/
```

```
→ docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

Starting 19fd4b6d78c4_temp_reverse_1 ... done
Attaching to 19fd4b6d78c4_temp_reverse_1
# ... service works fine ...
```

**Describe the results you expected:**

Container is started without any errors

**Additional information you deem important (e.g. issue happens only occasionally):**

```
→ docker-compose config
services:
  reverse:
    hostname: reverse
    image: openresty/openresty:alpine
    ports:
    - published: 443
      target: 443
    volumes:
    - /Users/vadimklimenko/Projects/temp/docker/nginx/conf:/etc/nginx/conf.d:rw
version: '3.8'
```

```
→ docker compose config
services:
  reverse:
    hostname: reverse
    image: openresty/openresty:alpine
    networks:
      default: null
    ports:
    - mode: ingress
      target: 443
      published: 443
      protocol: tcp
    volumes:
    - type: bind
      source: /Users/vadimklimenko/Projects/temp/docker/nginx/conf
      target: /etc/nginx/conf.d
networks:
  default:
    name: temp_default
```

This compose file is valid for `docker-compose`, but not for `docker compose`.
[By documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes), this notation is supported:
```
  # Path on the host, relative to the Compose file
  - ./cache:/tmp/cache
```

**Output of `docker-compose version`:**

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
➜  temp docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 88
  Running: 0
  Paused: 0
  Stopped: 88
 Images: 45
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 9.733GiB
 Name: docker-desktop
 ID: O7PI:WETW:DNF3:724N:4YOH:UN4Y:P5HX:KX27:NRMJ:T2GD:ASAG:EUPV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 46
  Goroutines: 53
  System Time: 2021-05-14T08:45:35.7579229Z
  EventsListeners: 6
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ndeloof** [comment] 2021-05-17 09:09
I can't reproduce this issue. `Duplicate mount point` is weird, as a single volume is declare I hardly imagine the possible cause for this

**Comment by ndeloof** [comment] 2021-05-17 09:11
I guess this is a side effect for https://github.com/docker/compose-cli/pull/1604
Engine error is pretty confusing here

Could you please try reproducing this issue with the latest 1.0.15 release ?
(you can get `docker-compose` binary from the release page tar.gz and install as a CLI plugin under `~/.docker/cli-plugins`)

**Comment by Vadimkin** [comment] 2021-05-17 10:05
@ndeloof thanks! I am using `v1.0.15` version, as proposed.

I see that it can't be reproduced for fresh container, but it's possible to reproduce when the same service was used by `docker-compose` previously.

So, my STRs:

```
➜ docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating temp_reverse_1 ... done
Attaching to temp_reverse_1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping temp_reverse_1 ... done
➜ docker compose up
[+] Running 0/0
 ⠋ Container temp_reverse_1  Recreate                                                                                                                                                                                                                      0.0s
Error response from daemon: Duplicate mount point: /etc/nginx/conf.d/

...

➜ docker rm d38d68dc214d
d38d68dc214d
➜ docker compose up
[+] Running 1/0
 ⠿ Container temp_reverse_1  Created                                                                                                                                                                                                                       0.0s
Attaching to reverse_1
... works fine ...
```

```
➜ docker-compose version
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

➜ docker compose version
Docker Compose version 2.0.0-beta.1%
```

One minor thing (might be related, but I am not sure) that some files were copied to `/etc/nginx/conf.d/` directory in the [base Dockerfile](https://github.com/openresty/docker-openresty/blob/master/alpine/Dockerfile#L159).

Let me know if you need more info

**Comment by ndeloof** [comment] 2021-05-17 10:21
Tried to reproduce as described, mixing `docker-compose` and `docker compose` commands, without success:
```
➜  /usr/local/bin/docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

Starting truc_reverse_1 ... done
Attaching to truc_reverse_1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping truc_reverse_1 ... done
➜  docker compose up
[+] Running 1/1
 ⠿ Container truc_reverse_1  Recreated                                                                                                                 0.1s
Attaching to reverse_1
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 0/1
 ⠋ Container truc_reverse_1  Stopping                                                                                                                  1.1s
canceled
```

**Comment by Vadimkin** [comment] 2021-05-17 10:38
Is it can be the issue that images were builded in the different way? They are a little bit different (about volumes format, especially):

![image](https://user-images.githubusercontent.com/2240404/118475057-7419aa00-b714-11eb-9931-367f271a4923.png)
![image](https://user-images.githubusercontent.com/2240404/118475081-7c71e500-b714-11eb-9b7c-48d57b9678a9.png)
![image](https://user-images.githubusercontent.com/2240404/118475152-8bf12e00-b714-11eb-9719-68060089e925.png)
![image](https://user-images.githubusercontent.com/2240404/118475297-bfcc5380-b714-11eb-916a-a77db49d7c36.png)


Image from docker-compose:
```
[
    {
        "Id": "b889ea3528a15907fa293906861a6a5ea411206592076afd1a3d88738edcc086",
        "Created": "2021-05-17T10:26:17.397903522Z",
        "Path": "/usr/local/openresty/bin/openresty",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-05-17T10:26:20.30272108Z",
            "FinishedAt": "2021-05-17T10:26:26.328691649Z"
        },
        "Image": "sha256:be670346a0abb051b0eccea572ea91e1afe01a9e9a781c3c55602609dc0dde13",
        "ResolvConfPath": "/var/lib/docker/containers/b889ea3528a15907fa293906861a6a5ea411206592076afd1a3d88738edcc086/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b889ea3528a15907fa293906861a6a5ea411206592076afd1a3d88738edcc086/hostname",
        "HostsPath": "/var/lib/docker/containers/b889ea3528a15907fa293906861a6a5ea411206592076afd1a3d88738edcc086/hosts",
        "LogPath": "/var/lib/docker/containers/b889ea3528a15907fa293906861a6a5ea411206592076afd1a3d88738edcc086/b889ea3528a15907fa293906861a6a5ea411206592076afd1a3d88738edcc086-json.log",
        "Name": "/b889ea3528a1_temp_reverse_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/Users/vadimklimenko/Projects/temp/docker/nginx/conf:/etc/nginx/conf.d:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "temp_default",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/4bdc18484d3fb28e17d76aeb1bd0c1a724c51d910abcd96c05a302644e212db6-init/diff:/var/lib/docker/overlay2/adcf88830e3497f53ed3d9493e6d6e2c47740dcd324d273eff7f40b095c1f18a/diff:/var/lib/docker/overlay2/e10d562a60925c506029ca6a4388ac7cb96f4d7acf9c2e35e61374d3d580955c/diff:/var/lib/docker/overlay2/c10c51c74c5cf032959b60141305f722389168123ff3666eb75aa0c0e6a045d5/diff:/var/lib/docker/overlay2/7f4af59bacfea23adb4ea2cbba6601c74b543589599e5d5d91452210a0ab53e3/diff",
                "MergedDir": "/var/lib/docker/overlay2/4bdc18484d3fb28e17d76aeb1bd0c1a724c51d910abcd96c05a302644e212db6/merged",
                "UpperDir": "/var/lib/docker/overlay2/4bdc18484d3fb28e17d76aeb1bd0c1a724c51d910abcd96c05a302644e212db6/diff",
                "WorkDir": "/var/lib/docker/overlay2/4bdc18484d3fb28e17d76aeb1bd0c1a724c51d910abcd96c05a302644e212db6/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/vadimklimenko/Projects/temp/docker/nginx/conf",
                "Destination": "/etc/nginx/conf.d",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "reverse",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin"
            ],
            "Cmd": [
                "/usr/local/openresty/bin/openresty",
                "-g",
                "daemon off;"
            ],
            "Image": "openresty/openresty:alpine",
            "Volumes": {
                "/etc/nginx/conf.d": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "b88168857591ac943e8139ee592f126d386a00bd9d5dd8c16b7cff690a559f93",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "temp",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/Users/vadimklimenko/Projects/temp",
                "com.docker.compose.service": "reverse",
                "com.docker.compose.version": "1.29.1",
                "maintainer": "Evan Wies \u003cevan@neomantra.net\u003e",
                "resty_add_package_builddeps": "",
                "resty_add_package_rundeps": "",
                "resty_config_deps": "--with-pcre     --with-cc-opt='-DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include'     --with-ld-opt='-L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib'     ",
                "resty_config_options": "    --with-compat     --with-file-aio     --with-http_addition_module     --with-http_auth_request_module     --with-http_dav_module     --with-http_flv_module     --with-http_geoip_module=dynamic     --with-http_gunzip_module     --with-http_gzip_static_module     --with-http_image_filter_module=dynamic     --with-http_mp4_module     --with-http_random_index_module     --with-http_realip_module     --with-http_secure_link_module     --with-http_slice_module     --with-http_ssl_module     --with-http_stub_status_module     --with-http_sub_module     --with-http_v2_module     --with-http_xslt_module=dynamic     --with-ipv6     --with-mail     --with-mail_ssl_module     --with-md5-asm     --with-pcre-jit     --with-sha1-asm     --with-stream     --with-stream_ssl_module     --with-threads     ",
                "resty_config_options_more": "",
                "resty_eval_post_make": "",
                "resty_eval_pre_configure": "",
                "resty_image_base": "alpine",
                "resty_image_tag": "3.13",
                "resty_openssl_patch_version": "1.1.1f",
                "resty_openssl_url_base": "https://www.openssl.org/source",
                "resty_openssl_version": "1.1.1k",
                "resty_pcre_version": "8.44",
                "resty_version": "1.19.3.1"
            },
            "StopSignal": "SIGQUIT"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "218d94521ffc1884411fdc9bf42a52b53fccea125160377dba52a68f218ff75e",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/218d94521ffc",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "temp_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "reverse",
                        "b889ea3528a1"
                    ],
                    "NetworkID": "5f2db6c2721f3a7bf596b8e4578857fbf823cf8345907f42b5b28a80ec572f0d",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

docker compose:
```
[
    {
        "Id": "a0864131e6b57e9ec3cabcf7f97cae359415e257f75aa91416182da709087ff4",
        "Created": "2021-05-17T10:30:58.794984193Z",
        "Path": "/usr/local/openresty/bin/openresty",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-05-17T10:31:01.798422259Z",
            "FinishedAt": "2021-05-17T10:31:04.692941553Z"
        },
        "Image": "sha256:be670346a0abb051b0eccea572ea91e1afe01a9e9a781c3c55602609dc0dde13",
        "ResolvConfPath": "/var/lib/docker/containers/a0864131e6b57e9ec3cabcf7f97cae359415e257f75aa91416182da709087ff4/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/a0864131e6b57e9ec3cabcf7f97cae359415e257f75aa91416182da709087ff4/hostname",
        "HostsPath": "/var/lib/docker/containers/a0864131e6b57e9ec3cabcf7f97cae359415e257f75aa91416182da709087ff4/hosts",
        "LogPath": "/var/lib/docker/containers/a0864131e6b57e9ec3cabcf7f97cae359415e257f75aa91416182da709087ff4/a0864131e6b57e9ec3cabcf7f97cae359415e257f75aa91416182da709087ff4-json.log",
        "Name": "/temp_reverse_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "temp_default",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/Users/vadimklimenko/Projects/temp/docker/nginx/conf",
                    "Target": "/etc/nginx/conf.d/"
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/5564aa29ae8659334274280e5038a730c984a6d1ff673860731afcdf0693d038-init/diff:/var/lib/docker/overlay2/adcf88830e3497f53ed3d9493e6d6e2c47740dcd324d273eff7f40b095c1f18a/diff:/var/lib/docker/overlay2/e10d562a60925c506029ca6a4388ac7cb96f4d7acf9c2e35e61374d3d580955c/diff:/var/lib/docker/overlay2/c10c51c74c5cf032959b60141305f722389168123ff3666eb75aa0c0e6a045d5/diff:/var/lib/docker/overlay2/7f4af59bacfea23adb4ea2cbba6601c74b543589599e5d5d91452210a0ab53e3/diff",
                "MergedDir": "/var/lib/docker/overlay2/5564aa29ae8659334274280e5038a730c984a6d1ff673860731afcdf0693d038/merged",
                "UpperDir": "/var/lib/docker/overlay2/5564aa29ae8659334274280e5038a730c984a6d1ff673860731afcdf0693d038/diff",
                "WorkDir": "/var/lib/docker/overlay2/5564aa29ae8659334274280e5038a730c984a6d1ff673860731afcdf0693d038/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/host_mnt/Users/vadimklimenko/Projects/temp/docker/nginx/conf",
                "Destination": "/etc/nginx/conf.d",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "reverse",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "443/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin"
            ],
            "Cmd": [
                "/usr/local/openresty/bin/openresty",
                "-g",
                "daemon off;"
            ],
            "Image": "sha256:be670346a0abb051b0eccea572ea91e1afe01a9e9a781c3c55602609dc0dde13",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "dbeb7d782ffc48f173e275d7abbf822ebe3473102ff42a20cc83fa0c5ca4a30b",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "temp",
                "com.docker.compose.project.config_files": "/Users/vadimklimenko/Projects/temp/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/Users/vadimklimenko/Projects/temp",
                "com.docker.compose.service": "reverse",
                "com.docker.compose.version": "1.0-alpha",
                "maintainer": "Evan Wies \u003cevan@neomantra.net\u003e",
                "resty_add_package_builddeps": "",
                "resty_add_package_rundeps": "",
                "resty_config_deps": "--with-pcre     --with-cc-opt='-DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include'     --with-ld-opt='-L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib'     ",
                "resty_config_options": "    --with-compat     --with-file-aio     --with-http_addition_module     --with-http_auth_request_module     --with-http_dav_module     --with-http_flv_module     --with-http_geoip_module=dynamic     --with-http_gunzip_module     --with-http_gzip_static_module     --with-http_image_filter_module=dynamic     --with-http_mp4_module     --with-http_random_index_module     --with-http_realip_module     --with-http_secure_link_module     --with-http_slice_module     --with-http_ssl_module     --with-http_stub_status_module     --with-http_sub_module     --with-http_v2_module     --with-http_xslt_module=dynamic     --with-ipv6     --with-mail     --with-mail_ssl_module     --with-md5-asm     --with-pcre-jit     --with-sha1-asm     --with-stream     --with-stream_ssl_module     --with-threads     ",
                "resty_config_options_more": "",
                "resty_eval_post_make": "",
                "resty_eval_pre_configure": "",
                "resty_image_base": "alpine",
                "resty_image_tag": "3.13",
                "resty_openssl_patch_version": "1.1.1f",
                "resty_openssl_url_base": "https://www.openssl.org/source",
                "resty_openssl_version": "1.1.1k",
                "resty_pcre_version": "8.44",
                "resty_version": "1.19.3.1"
            },
            "StopSignal": "SIGQUIT"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "1b6d6336fb41349f067c13e7813928c079832f49d8634ee3f910a79690472824",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/1b6d6336fb41",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "temp_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "reverse",
                        "temp_reverse_1",
                        "a0864131e6b5"
                    ],
                    "NetworkID": "5f2db6c2721f3a7bf596b8e4578857fbf823cf8345907f42b5b28a80ec572f0d",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by ndeloof** [comment] 2021-05-17 14:04
docker (space) compose uses the modern "mount" API, but for bind mounts due to distinct behaviour for some corner cases, that we can't manage by the existing API. https://github.com/docker/compose-cli/pull/1604 try to balance this, and you should have seen the bind API in use with your config. Makes me wonder you're actually running 1.0.15 - can you check `docker compose version `report 2.0-beta.2`?

**Comment by Vadimkin** [comment] 2021-05-17 14:35
@ndeloof sorry, looks like you're correct! I used incorrect package

With 2.0.0 the issue is the same, but looks like the source of this error is slash.

```
➜ docker compose version
Docker Compose version 2.0.0-beta.2
```

The major difference is slash at the end of destination directory:

![image](https://user-images.githubusercontent.com/2240404/118505587-37aa7600-b735-11eb-8d4d-4a4e7d3c0cd6.png)
![image](https://user-images.githubusercontent.com/2240404/118505812-6fb1b900-b735-11eb-954e-d45c92f8d242.png)


[docker compose.log](https://github.com/docker/compose-cli/files/6494474/docker.compose.log)
[docker-compose.log](https://github.com/docker/compose-cli/files/6494476/docker-compose.log)

**Comment by ndeloof** [comment] 2021-05-18 08:14
can you please confirm this assumption by updating your compose file so that `volumes` uses trailing `/` for bind mount paths?
then remove all existing containers, and compare `docker-compose up` vs `docker compose up`.

**Comment by Vadimkin** [comment] 2021-05-18 09:46
Sorry, looks like I messed up with STRs. If volume is with slash (`./docker/nginx/conf/:/etc/nginx/conf.d/`), then I am not able to run `docker-compose` and then `docker compose` (all previous logs are related to `docker-compose.yml` with slash)

With next `docker-compose.yml` I am able to run `docker-compose up` and then `docker compose up`:
```
version: '3.8'
services:
    reverse:
        hostname: reverse
        image: openresty/openresty:alpine
        ports:
            - "443:443"
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d
```

Volumes are the same:
![image](https://user-images.githubusercontent.com/2240404/118629458-439a4480-b7d6-11eb-8e56-58a23814ffe5.png)

[docker compose.log](https://github.com/docker/compose-cli/files/6500159/docker.compose.log)
[docker-compose.log](https://github.com/docker/compose-cli/files/6500160/docker-compose.log)

Sorry again for bad STRs 🤦‍♂️

**Comment by ndeloof** [comment] 2021-06-21 07:14
Issue has been fixed by https://github.com/docker/compose-cli/pull/1782

**Closed by ndeloof** 2021-06-21 07:14 UTC
Labels: compatibility
