### ISSUE TITLE
Windows bug: Dockerfile not resolved for build ("Dockerfile: no such file or directory")

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1854] opened 2021-06-28 20:52 UTC
**Description**

On WIndows, a simple docker-compose.yaml with a build section fails:

**Steps to reproduce the issue:**

~/.ddev/.ssh-auth-compose-full.yaml:
```yaml
services:
  ddev-ssh-agent:
    build:
      context: C:\Users\testbot\.ddev\.sshimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: drud/ddev-ssh-agent:v1.17.0
        gid: "1000"
        uid: "1000"
        username: testbot
    image: drud/ddev-ssh-agent:v1.17.0-built
    user: 1000:1000
```

~/.ddev/sshimageBuild/Dockerfilie:
```yaml

ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG username
ARG uid
ARG gid
RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
```

**Describe the results you received:**

```bash
$ docker-compose -f .ssh-auth-compose-full.yaml up --build
#1 [internal] load build definition from Dockerfile
#1 sha256:cd03aa6f24097397238629ca643a2d41ced92eaa8250684cb87f3b4e494fffe7
#1 transferring dockerfile:
#1 transferring dockerfile: 2B done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 sha256:809da1da9394d232f03057a5ef9b6f835e72346426b85f4de62613a2a8ff9be9
#2 transferring context: 2B done
#2 DONE 0.1s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount219989023/Dockerfile: no such file or directory
```

**Describe the results you expected:**

This exact thing works perfectly on macOS with compose v2 as in docker desktop v3.5.1

You get the same result (Windows) with `docker compose -f .ssh-auth-compose-full.yaml up`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker context show`:**  

```
desktop-linux
```

**Output of `docker info`:**

```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.121GiB
 Name: docker-desktop
 ID: OJCD:6RDM:BGJL:44VA:5NDF:JE65:CIXD:TRGG:XWIC:BYQD:5JRK:NCAG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Windows 10 native (not WSL2), Docker Desktop 3.5.1

**Comment by rfay** [comment] 2021-06-30 01:39
This is easily recreatable on another machine, and I also checked WSL2 - works fine on WSL2.

**Comment by rfay** [comment] 2021-06-30 03:46
Weird... I went looking in the [compose spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md) to see if somehow "dockerfile" was being done wrong (works fine on macOS and WSL2 though)... and I can't find any definition of the `build:` stanza in there at all. It's certainly [there in the v3 spec](https://docs.docker.com/compose/compose-file/compose-file-v3/#build)

**Comment by rfay** [comment] 2021-06-30 03:48
Just this simple thing gets the failure:

```yaml
services: 
  ddev-ssh-agent:
     build: 
      context: 'C:\Users\rfay\.ddev\.sshimageBuild'
       dockerfile: 'C:\Users\rfay\.ddev\.sshimageBuild\Dockerfile'
     image: drud/ddev-ssh-agent:v1.17.0-built 
```

you do have to do `docker-compose -f file.yaml up --build` though - doesn't fail without.the --build

**Comment by rfay** [comment] 2021-06-30 04:38
AFAICT, Windows paths are not accepted, or at least full Windows paths are not accepted for `dockerfile:` or `context:`, and that's the reason for this #fail. 

I may have it fixed by using relative paths in https://github.com/drud/ddev/pull/3078

**Comment by ndeloof** [comment] 2021-06-30 08:21
I can confirm issue building service images when an absolute context path is being used, investigating for a fix

**Comment by ndeloof** [comment] 2021-06-30 08:34
made a simpler reproduction scenario:
```yaml
services:
  test:
    context: .
    dockerfile: Dockerfile.test
```

`docker compose build` fail as `no such file or directory` accessing the custom Dockerfile. Obviously only happens on Windows.

**Comment by ndeloof** [comment] 2021-06-30 08:53
I noticed, on windows, `docker compose config` shows the service.build.dockerfile is overridden to the default `Dockerfile` value, which explain this bug. investigating

**Comment by ndeloof** [comment] 2021-06-30 08:55
@rfay using relative paths probably won't fix this issue as internally compose.v2 makes all paths absolute when the compose file(s) get loaded.

**Comment by ndeloof** [comment] 2021-06-30 10:30
I eventually understood the root cause for this whole crazyness:
build context can be set as a git URL without a dedicated syntax to disambiguate things :'( 
We use `url.Parse` to guess the context is an URL or a file path. This used to work ... until context path is something like `C:\foo\bar`, which get parsed as a valid URL, with scheme `C`.

**Comment by ndeloof** [comment] 2021-06-30 12:43
this unfortunately is not a new challenge to distinguish remote URL being used as context vs local path, see https://github.com/moby/moby/issues/33686#issuecomment-308748173

**Closed** 2021-06-30 13:34 UTC

**Comment by rfay** [comment] 2021-06-30 18:47
Amazingly, the relative-path approach seems to have worked ok. Just manually tested https://github.com/drud/ddev/pull/3078 on Windows and it works now with compose-cli.

**Comment by ndeloof** [comment] 2021-06-30 19:03
yes, using a relative path prevents mis-parsing the context as a valid URL.
