### ISSUE TITLE
Compose parsing commented out yaml for env vars

### ISSUE THREAD

**Issue by beyondmeat** [docker/compose-cli#2028] opened 2021-08-19 02:27 UTC
**Description**

I discovered that commented out yaml that contain env vars in the comment do get parsed in RC1. This seems to be a bug introduced by the recent env changes.

for example a commented out docker label, demoted by #
```
# traefik.http.routers.dashboard.rule: Host(`${TRAEFIK_CNAME}.localhost`, `${TRAEFIK_CNAME}.local.${DOMAIN}`)
```

It will output warn on pull or up about the env variable. The env var isn't used or referenced by anything that isn't commented out. 

have valid yml that uses a env variable
comment out the line in the yml, (line starting with #)
run docker compose pull to 
**Steps to reproduce the issue:**
1. Create docker compose and use env file with env var
2. Comment out a line that uses a unique env var
3. Run pull or up

**Describe the results you received:**
see variable is not set. Defaulting to a blank string warning.

**Describe the results you expected:**
Not to see a warning. Compose must be parsing commented out yaml lines in it's env parsing code as that is the likely explanation.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`:**
```
RC1
```

**Output of `docker version`:**
```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```

```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by rowanparker** [comment] 2021-08-24 04:57
This may be related. It seems lines with `$` characters cause issues. I have the following line in a docker-compose.yaml

`      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}`

With Docker Compose V2 enabled, I get an error and my containers won't launch.

`yaml: line 9: did not find expected tag URI`

If I disable Docker Compose V2, the error goes away.

The worst part is I never went in and set this value to enabled. I suspect it was silently enabled as per this article:
https://docs.docker.com/compose/cli-command/

`We will gradually turn this option on automatically for Docker Desktop users, so that users can seamlessly move to Docker Compose V2 without the need to upgrade any of their scripts.`

So I just wasted an hour troubleshooting this because Docker just changes things on you with no notification.

**Comment by ndeloof** [comment] 2021-08-24 08:42
Will be fixed by https://github.com/compose-spec/compose-go/pull/167 AFAICT

**Comment by beyondmeat** [comment] 2021-09-09 21:37
@ulyssessouza please reopen, bug still valid in rc3

**Comment by ulyssessouza** [comment] 2021-09-10 07:58
@beyondmeat Could you please post a minimal `docker-compose.yml` to reproduce the case?

**Comment by beyondmeat** [comment] 2021-09-10 11:04
Any compose file will do that uses extends. When the commented out variable exists in an a compose file that is referenced by another compose file via extends, it parses the commended out var and warns it's not set. This is only occuring for extended compose files. Should I make a new issue on docker/compose since it belongs there now?

docker-compose.yml
```
version: "3.9"

services:
  whoami:
    extends:
      file: ./docker-compose.whoami.yml
      service: whoami
```

docker-compose.whoami.yml
```
version: "3.9"

services:
  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.${THIS_IS_A_BUG}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
```

**Comment by ndeloof** [comment] 2021-09-10 12:50
Closed => https://github.com/docker/compose/issues/8603

**Closed by ndeloof** 2021-09-10 12:50 UTC
