### ISSUE TITLE
Line wrapping issue typing long commands

### ISSUE THREAD

**Issue by kevinsjoberg** [docker/compose-cli#1640] opened 2021-05-05 07:29 UTC
**Description**

The issue described in https://github.com/docker/compose/issues/253 seem to manifest itself for compose-cli. Long lines wrap on the same lines, effectively overwriting the current line with new contents. See https://asciinema.org/a/yl7bId85NqXIsb9xkqAFnsBsD for a demonstration.

**Steps to reproduce the issue:**
1. Run `docker compose run --rm <some_service> bash`.
2. Type in a long line until the line wraps and effectively starts overwriting the beginning of the current line.

**Describe the results you received:**

When the line wraps, it wraps from the beginning of the current line, effectively overwriting the current line.

**Describe the results you expected:**

I don't expect line wrapping to overwrite previous contents.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 12
  Running: 5
  Paused: 0
  Stopped: 7
 Images: 18
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: H3EY:JFAI:YX2P:RMEH:YA3I:O6KF:XHGB:ZKNH:5EQO:IJQ4:Y5MY:D3LI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by mhenrixon** [comment] 2021-05-05 07:31
Possibly related issue: https://github.com/docker/compose/issues/253

**Comment by ndeloof** [comment] 2021-05-05 08:22
I ran a quick test using latest 1.0.14 and can't reproduce (https://asciinema.org/a/JleQ3WPtYOlYp14a9PQhlRw1f)

as you're recording demonstrate container's pseudo tty isn't adjusted to your actual terminal widht, I assume this might have been fixed by https://github.com/docker/compose-cli/pull/1512

Would you mind testing 1.0.14 (can download from github release, just place `docker-compose` binary into `~/.docker/cli-plugins`.

**Comment by mhenrixon** [comment] 2021-05-05 09:41
@ndeloof when might that version be released for Docker For Mac?

Personally I just got used to it and it stopped annoying me so no big deal for this guy, just curious.

**Comment by kevinsjoberg** [comment] 2021-05-05 11:35
@ndeloof I can confirm that this issue is no longer present in `1.0.14`. 🎉

**Comment by mhenrixon** [comment] 2021-05-05 11:55
Actually, I just upgraded to Docker For Mac 3.3.2 and the problem has been fixed! It seems a problem with having to `ctrl+c` to in the console has also been fixed.

**Comment by ndeloof** [comment] 2021-05-05 12:24
thanks a lot for your feedback

**Closed by ndeloof** 2021-05-05 12:24 UTC
Labels: bug 🐞, compose
