### ISSUE TITLE
Run --volumes replaces volumes instead of merging

### ISSUE THREAD

**Issue by joelossher** [docker/compose-cli#1974] opened 2021-07-30 19:29 UTC
**Description**

I'm seeing different behavior between `docker-compose` v1 and the new `docker compose` for the `-v` flag.

In v1, the `-v` flag merges the mounts with those present in the `docker-compose.yml` (introduced [here](https://github.com/docker/compose/pull/4954)). In v2 it appears that we're back to the old behavior of mounts being replaced.

**Steps to reproduce the issue:**
1. Start with this `docker-compose.yml`
```yml
version: '3.8'

services:
  example:
    image: alpine:latest
    volumes:
      - ./test-compose:/app/test-compose
    command: ls /app
    working_dir: /app
```
2. Using v1 docker-compose, run:
```
❯ docker-compose -p example run --rm -v "$(pwd)/test-script:/app/test-command" example
Creating example_example_run ... done
test-compose  test-command
```
3. Using `docker compose`, run:
```
❯ docker compose -p example run --rm -v "$(pwd)/test-script:/app/test-command" example
test-command
```

**Describe the results you received:**
When using v2, only the volume mounted from the command line is present.

**Describe the results you expected:**
I would expect to see the same behavior as in v1, where the mounts from the `docker-compose.yml` are preserved and both directories are present.

**Additional information you deem important (e.g. issue happens only occasionally):**
As expected, I see the same problematic behavior when v2 is turned on and `docker-compose` is replaced with the new `docker compose`.

**Output of `docker-compose --version`: ***
```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker version`:**

```
Docker version 20.10.7, build f0df350
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 32
  Running: 2
  Paused: 0
  Stopped: 30
 Images: 218
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: Q55N:E67C:LAUB:2GZY:3JWE:7OQT:LQM2:PYQS:PCX4:UOYY:R4BH:BFPW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Running locally on a mac.

**Comment by ndeloof** [comment] 2021-08-06 07:03
fixed by https://github.com/compose-spec/compose-go/pull/161

**Closed by ndeloof** 2021-08-06 07:03 UTC
Labels: bug 🐞, compatibility

**Comment by joelossher** [comment] 2021-08-06 12:50
Awesome, thanks for the quick turnaround!

**Comment by mattshin** [comment] 2021-08-13 21:40
Is there a way to replicate the old behavior? Specifically, to `docker-compose run ...` via CLI and _not_ mount any of the volumes that are in the `docker-compose.yaml` file?

In my specific use case, we want to use `docker-compose` for _both_ local development _and_ testing in the CI environment. However, the CI env not only [disregards volume mounts](https://circleci.com/docs/2.0/building-docker-images/#mounting-folders) (understandable), if there is a volume mount in the docker-compose, it *deletes* the target directory. We already have a work around that allows us to volume mount locally, but it uses multiple docker-compose services and/or override files. 

The bug that was just fixed obviously could have been used, but it was a bug. Is there a way to replicate the unintended behavior in this issue intentionally?

I apologize, I know this is somewhat off topic but I noticed recent activity here and the only other thread I could find that is similar refers to an overrides file, which is not as relevant (https://github.com/docker/compose/issues/3729). If I should open a new issue for this, I'm happy to, but I was hoping that someone would have a quick answer for me here.
