### ISSUE TITLE
Upgrading to Mac Docker Desktop 3.0.0 Causing Mounts Denied: path/to/file: file does not exist Error 

### ISSUE THREAD

**Issue by clpatterson** [docker/compose-cli#1043] opened 2020-12-10 17:24 UTC
**Description**
After upgrading to latest version of Docker Desktop for Mac 3.0.0, docker-compose up --build cmd throws the errors below that are preventing me from spinning up my containerized hobby project (a simple Python REST API). This error smells like a bug introduced by 3.0.0 because when I revert to 2.5.0.0 the issue goes away and I'm able to build my image and spin up my container without issue. The file/directory referenced in the error message does exist and has the following permissions: drwxr-xr-x. Any help resolving this issue would be great. If error is on my side, please let me know where I've strayed. Thanks!

```
ERROR: for <service_name> Cannot start service <service_name>: Mounts denied: approving path/to/project/root/dir: file does not exist
ERROR: Encountered errors while bringing up the project.
```

**Steps to reproduce the issue:**
1. clone code locally https://github.com/clpatterson/hotel_api.git
2. docker-compose up --build (executed in project root dir)

**Describe the results you received:**
The following error that prevents the container from being spun up.

```
Successfully built 34141e8d249d
Successfully tagged hotel_api_api:latest
hotel_api_postgres_1 is up-to-date
Recreating e98f9b0e1ab8_hotel_api_api_1 ... error

ERROR: for e98f9b0e1ab8_hotel_api_api_1  Cannot start service api: Mounts denied: approving path/to/project/root/dir: file does not exist

ERROR: for api  Cannot start service api: Mounts denied: approving path/to/project/root/dir: file does not exist
ERROR: Encountered errors while bringing up the project.
```

**Describe the results you expected:**
Expected this command would launch my multi-container environment successfully (as it would for version before 3.0.0).

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 143
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: 3KHR:7KUH:5DF2:PGBF:NIND:KUJK:YHCC:RWMB:XLRI:M4QA:TRQL:NYQ2
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 43
  Goroutines: 56
  System Time: 2020-12-10T17:05:01.244138646Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by ClaytonNorthey92** [comment] 2020-12-10 18:02
I am getting the same issue when upgrading to `3.0.0`, when downgrading to `2.5.5` the issue goes away as well.

**Comment by robertbaker** [comment] 2020-12-10 18:17
wrong project

**Comment by sfcgeorge** [comment] 2020-12-10 18:21
I get the issue running `docker compose up` too but it seems to be a Docker For Mac issue more than anything: https://github.com/docker/for-mac/issues/4975

**Comment by robertbaker** [comment] 2020-12-10 18:21
issue needs moved to https://github.com/docker/compose

This is the wrong repo for this.

**Comment by stephen-turner** [comment] 2020-12-10 19:08
Closing as dupe of docker/for-mac#5115.

**Closed by stephen-turner** 2020-12-10 19:08 UTC

**Comment by clpatterson** [comment] 2020-12-10 19:41
Thanks! Will follow the docker/for-mac issue.
