### ISSUE TITLE
cannot use control characters in terminals via 'run' that work via 'up' + 'exec'

### ISSUE THREAD

**Issue by jakeonfire** [docker/compose-cli#1908] opened 2021-07-09 21:15 UTC
**Description**
When running a terminal shell via `docker compose run`, control characters like control, option/meta, and arrow keys do not work.

**Steps to reproduce the issue:**
1. write a simple `docker-compose.yml` like:
```
version: "3.8"
services:
  app:
    image: ubuntu:latest
```
2. start a shell with `docker compose run app bash`
3. (type a few characters, then) try any control keys, like ←, CTRL+A, META+←

**Describe the results you received:**
control characters are printed to the console, like `^[[D^A^[b`.

**Describe the results you expected:**
the commands should work as they do when following the same steps but with `docker compose up` and `docker compose exec app bash` for step # 2.

**Additional information you deem important (e.g. issue happens only occasionally):**
i suspect this may be related to https://github.com/docker/compose-cli/issues/1151

**Output of `docker compose version`:**
```
Docker Compose version v2.0.0-beta.6
```
(BTW this step should be updated in the template from "**Output of `docker-compose --version`: ***"

**Output of `docker version`:**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
```
default
```

**Output of `docker info`:**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 34
  Running: 13
  Paused: 0
  Stopped: 21
 Images: 288
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.776GiB
 Name: docker-desktop
 ID: 3XSZ:KTXH:X6XJ:UA4Y:32LE:UGDP:6THV:24OE:JLRL:R3UU:4VDF:6YJS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment] 2021-07-12 06:50
duplicates https://github.com/docker/compose-cli/issues/1461

**Comment by jakeonfire** [comment] 2021-07-13 08:20
signals and control characters are the same issue?

**Comment by ndeloof** [comment] 2021-07-13 08:28
yes, passing signals require to configure the terminal in raw "character" mode, which is also the reason you don't get control sequences forwarded

**Comment by dmolesUC** [comment] 2021-07-16 17:02
What's the workaround? Using `up` + `exec` isn't always an option, if you have some reason you don't actually want to start the service (e.g., debugging why the service doesn't start). `docker run <full image name>`?

**Comment by ndeloof** [comment] 2021-07-19 09:47
re-opening this issue so we can confirm it get fixed once #1461 has been addressed (this deserves more tests)

**Comment by ndeloof** [comment] 2021-07-20 07:46
regression was introduced by https://github.com/docker/compose-cli/commit/b6552cd93505d8b70fceed507c624618bc240da3#diff-083bba80b4f97675e48a3daec9da3a101a36282dc9cb8e8530fc30b7ef9c883cR81

**Comment by twelvelabs** [comment] 2021-07-23 00:25
I don't know if it's related, but I am also seeing all my shell commands echoed out:

```
docker compose run app bash

$ echo "something"
echo "something"
something
```

Stopped once I went back to the original `docker-compose` implementation (along w/ the control char behavior).

**Closed** 2021-07-26 06:22 UTC
Labels: bug: regression ↩️

**Comment by codytowstik** [comment] 2022-01-28 22:49
This is still happening to me using Docker for Mac on `3.5.2`

I see the same behavior mentioned above
1. Echo is duplicated
2. Control characters are displayed like `^[[D^A^[b` when using arrow keys for `run` only but not `exec`
3. Only an issue when using `docker compose` rather than `docker-compose`
