### ISSUE TITLE
automate publication of docker/ecs-secrets-sidecar image

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#660] opened 2020-09-25 10:14 UTC
**Description**
secret support uses sidecar container code from https://github.com/docker/compose-cli/tree/main/ecs/secrets
published as https://hub.docker.com/r/docker/ecs-secrets-sidecar

building this image from source should be automated

**Comment by gtardif** [comment] 2020-09-28 09:31
duplicate of #669

**Closed by gtardif** 2020-09-28 09:31 UTC
Labels: ecs
