### ISSUE TITLE
unable to select login to different Azure cloud

### ISSUE THREAD

**Issue by bb5178** [docker/compose-cli#749] opened 2020-10-08 17:17 UTC
Cloud Integration 0.1.18

As-title: docker login azure command have no option to select different Azure cloud (AzureCloud, Azure ChinaCloud, AzureUSGovernment, and AzureGermanCloud)

**Comment by karolz-ms** [comment] 2020-10-08 17:25
Duplicate of https://github.com/docker/compose-cli/issues/658

**Comment by gtardif** [comment] 2020-10-09 12:56
closing as duplicate

**Closed by gtardif** 2020-10-09 12:56 UTC
